AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 FTP Server with CloudWatch Logging and S3 Integration'

Parameters:
  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 instance type

  S3BucketName:
    Type: String
    Description: S3 bucket for FTP file uploads

  FTPUser:
    Type: String
    Description: FTP username
    NoEcho: false

  FTPPassword:
    Type: String
    Description: FTP password
    NoEcho: true

  KeyName:
    Type: String
    Description: EC2 Key Pair name (optional, not used for external access)
    Default: ''

  DomainName:
    Type: String
    Description: Domain name to create/update in Route53 (optional)
    Default: ''

  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID (required if DomainName is provided)
    Default: ''

Conditions:
  HasKeyName: !Not [!Equals [!Ref KeyName, '']]
  HasDomainName: !Not [!Equals [!Ref DomainName, '']]

Resources:
  # VPC Configuration
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: FTP-Server-VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: FTP-Server-IGW

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: FTP-Server-PublicSubnet

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: FTP-Server-PublicRouteTable

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # Security Group - Only FTP port open
  FTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for FTP server - only port 29720
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 29720
          ToPort: 29720
          CidrIp: 0.0.0.0/0
          Description: FTP Control Port
        # Passive FTP ports
        - IpProtocol: tcp
          FromPort: 21000
          ToPort: 21100
          CidrIp: 0.0.0.0/0
          Description: FTP Passive Ports
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: FTP-Server-SG

  # IAM Role for EC2
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${S3BucketName}'
                  - !Sub 'arn:aws:s3:::${S3BucketName}/*'
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: '*'
        - PolicyName: Route53Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - route53:ListResourceRecordSets
                  - route53:ChangeResourceRecordSets
                  - route53:GetChange
                Resource: '*'

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  # CloudWatch Log Group
  FTPLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/ec2/ftp-server
      RetentionInDays: 7

  # EC2 Instance
  FTPServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Sub '{{resolve:ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/arm64/hvm/ebs-gp2/ami-id}}'
      KeyName: !If [HasKeyName, !Ref KeyName, !Ref 'AWS::NoValue']
      IamInstanceProfile: !Ref EC2InstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref FTPSecurityGroup
          SubnetId: !Ref PublicSubnet
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp3
            VolumeSize: 10
            DeleteOnTermination: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e

          # Log everything to a file for debugging
          exec > >(tee -a /var/log/userdata.log)
          exec 2>&1

          echo "========================================="
          echo "Starting UserData script execution"
          echo "Timestamp: $(date)"
          echo "========================================="

          # Update system
          echo "Updating system packages..."
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -y
          apt-get upgrade -y

          # Install required packages
          echo "Installing required packages..."
          apt-get install -y vsftpd awscli wget
          echo "Packages installed successfully"

          # Install CloudWatch agent
          echo "Installing CloudWatch agent..."
          wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/arm64/latest/amazon-cloudwatch-agent.deb
          dpkg -i -E ./amazon-cloudwatch-agent.deb
          rm -f ./amazon-cloudwatch-agent.deb
          echo "CloudWatch agent installed"

          # Create FTP user
          echo "Creating FTP user: ${FTPUser}"
          useradd -m -s /bin/bash ${FTPUser}
          echo "${FTPUser}:${FTPPassword}" | chpasswd
          echo "FTP user created successfully"

          # Create FTP directory
          mkdir -p /home/${FTPUser}/ftp/upload
          chown -R ${FTPUser}:${FTPUser} /home/${FTPUser}/ftp
          chmod -R 755 /home/${FTPUser}/ftp

          # Configure vsftpd
          cat > /etc/vsftpd.conf << 'EOF'
          anonymous_enable=NO
          local_enable=YES
          write_enable=YES
          local_umask=022
          dirmessage_enable=YES
          xferlog_enable=YES
          xferlog_file=/var/log/vsftpd.log
          xferlog_std_format=YES
          connect_from_port_20=NO
          listen=YES
          listen_ipv6=NO
          listen_port=29720
          pam_service_name=vsftpd
          userlist_enable=YES
          userlist_deny=NO
          tcp_wrappers=NO
          pasv_enable=YES
          pasv_min_port=21000
          pasv_max_port=21100
          pasv_address=PUBLIC_IP_PLACEHOLDER
          chroot_local_user=YES
          allow_writeable_chroot=YES
          local_root=/home/$USER/ftp
          user_sub_token=$USER
          seccomp_sandbox=NO
          EOF

          # Get public IP and update config
          echo "Retrieving public IP address..."
          PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)

          if [ -z "$PUBLIC_IP" ]; then
              echo "ERROR: Failed to retrieve public IP address"
              exit 1
          fi

          echo "Public IP: $PUBLIC_IP"
          echo "Updating vsftpd configuration with public IP..."
          sed -i "s/PUBLIC_IP_PLACEHOLDER/$PUBLIC_IP/" /etc/vsftpd.conf

          # Verify the substitution worked
          if grep -q "PUBLIC_IP_PLACEHOLDER" /etc/vsftpd.conf; then
              echo "ERROR: Failed to replace PUBLIC_IP_PLACEHOLDER in vsftpd.conf"
              exit 1
          fi

          echo "vsftpd configuration updated successfully"

          # Update/Create Route53 DNS record if DOMAIN_NAME is provided
          DOMAIN_NAME="${DomainName}"
          HOSTED_ZONE_ID="${HostedZoneId}"

          if [ ! -z "$DOMAIN_NAME" ] && [ ! -z "$HOSTED_ZONE_ID" ]; then
              echo "Managing Route53 DNS record for $DOMAIN_NAME..."

              # Check if the record exists to provide better logging
              echo "Checking if DNS record exists for $DOMAIN_NAME..."
              EXISTING_RECORD=$(aws route53 list-resource-record-sets \
                  --hosted-zone-id "$HOSTED_ZONE_ID" \
                  --query "ResourceRecordSets[?Name=='$DOMAIN_NAME.' && Type=='A'].ResourceRecords[0].Value" \
                  --output text 2>/dev/null)

              if [ ! -z "$EXISTING_RECORD" ] && [ "$EXISTING_RECORD" != "None" ]; then
                  echo "Found existing A record pointing to: $EXISTING_RECORD"
                  echo "Will update to point to: $PUBLIC_IP"
                  ACTION_TYPE="Updating"
              else
                  echo "No existing A record found"
                  echo "Will create new A record pointing to: $PUBLIC_IP"
                  ACTION_TYPE="Creating"
              fi

              # Create change batch JSON (UPSERT will create if not exists, update if exists)
              cat > /tmp/route53-change.json << EOFROUTE53
          {
            "Changes": [{
              "Action": "UPSERT",
              "ResourceRecordSet": {
                "Name": "$DOMAIN_NAME",
                "Type": "A",
                "TTL": 300,
                "ResourceRecords": [{"Value": "$PUBLIC_IP"}]
              }
            }]
          }
          EOFROUTE53

              # Apply the change
              echo "$ACTION_TYPE A record for $DOMAIN_NAME..."
              CHANGE_ID=$(aws route53 change-resource-record-sets \
                  --hosted-zone-id "$HOSTED_ZONE_ID" \
                  --change-batch file:///tmp/route53-change.json \
                  --query 'ChangeInfo.Id' \
                  --output text)

              if [ $? -eq 0 ]; then
                  ACTION_LOWER=$(echo "$ACTION_TYPE" | tr '[:upper:]' '[:lower:]')
                  echo "Successfully $ACTION_LOWER DNS record. Change ID: $CHANGE_ID"

                  # Wait for the change to be applied
                  echo "Waiting for DNS change to propagate..."
                  aws route53 wait resource-record-sets-changed --id "$CHANGE_ID"
                  echo "DNS record is now active! $DOMAIN_NAME -> $PUBLIC_IP"
              else
                  ACTION_LOWER=$(echo "$ACTION_TYPE" | tr '[:upper:]' '[:lower:]')
                  echo "ERROR: Failed to $ACTION_LOWER DNS record"
              fi

              # Clean up
              rm -f /tmp/route53-change.json
          else
              echo "Skipping Route53 DNS update - DOMAIN_NAME or HOSTED_ZONE_ID not provided"
          fi

          # Add FTP user to allowed users
          echo "${FTPUser}" > /etc/vsftpd.user_list

          # Validate vsftpd configuration before starting
          echo "Validating vsftpd configuration..."
          if ! grep -q "pasv_address=" /etc/vsftpd.conf; then
              echo "ERROR: pasv_address not found in vsftpd.conf"
              exit 1
          fi

          PASV_ADDR=$(grep "pasv_address=" /etc/vsftpd.conf | cut -d'=' -f2)
          echo "Configured pasv_address: $PASV_ADDR"

          if [ "$PASV_ADDR" = "PUBLIC_IP_PLACEHOLDER" ]; then
              echo "ERROR: pasv_address still contains placeholder value"
              exit 1
          fi

          # Start vsftpd initially to test config
          echo "Starting vsftpd service (initial start)..."
          systemctl start vsftpd

          if [ $? -ne 0 ]; then
              echo "ERROR: Failed to start vsftpd service"
              echo "Checking vsftpd status..."
              systemctl status vsftpd || true
              echo "Checking vsftpd config..."
              cat /etc/vsftpd.conf
              exit 1
          fi

          systemctl enable vsftpd
          echo "vsftpd service started and enabled successfully"

          # Disable firewalld (using EC2 Security Group instead)
          echo "Disabling firewalld (EC2 Security Group handles firewall)..."
          systemctl stop firewalld 2>/dev/null || true
          systemctl disable firewalld 2>/dev/null || true
          echo "Firewall disabled - using EC2 Security Group for access control"

          # Create CloudWatch agent config
          cat > /opt/aws/amazon-cloudwatch-agent/etc/config.json << 'EOF'
          {
            "logs": {
              "logs_collected": {
                "files": {
                  "collect_list": [
                    {
                      "file_path": "/var/log/userdata.log",
                      "log_group_name": "/aws/ec2/ftp-server",
                      "log_stream_name": "userdata-{instance_id}"
                    },
                    {
                      "file_path": "/var/log/vsftpd.log",
                      "log_group_name": "/aws/ec2/ftp-server",
                      "log_stream_name": "vsftpd-{instance_id}"
                    },
                    {
                      "file_path": "/var/log/ftp-to-s3.log",
                      "log_group_name": "/aws/ec2/ftp-server",
                      "log_stream_name": "ftp-to-s3-{instance_id}"
                    }
                  ]
                }
              }
            }
          }
          EOF

          # Start CloudWatch agent
          /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
            -a fetch-config \
            -m ec2 \
            -s \
            -c file:/opt/aws/amazon-cloudwatch-agent/etc/config.json

          # Create S3 sync script
          cat > /usr/local/bin/ftp-to-s3.sh << 'EOFSCRIPT'
          #!/bin/bash

          FTP_DIR="/home/${FTPUser}/ftp"
          S3_BUCKET="${S3BucketName}"
          LOG_FILE="/var/log/ftp-to-s3.log"

          log() {
              echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> $LOG_FILE
          }

          log "Starting FTP to S3 sync"

          # Find files in upload directory
          find $FTP_DIR -type f -mmin +1 | while read file; do
              if [ -f "$file" ]; then
                  filename=$(basename "$file")
                  log "Processing file: $filename"

                  # Upload to S3
                  if aws s3 cp "$file" "s3://$S3_BUCKET/incoming/$filename"; then
                      log "Successfully uploaded $filename to S3"
                      rm -f "$file"
                      log "Deleted local file: $filename"
                  else
                      log "ERROR: Failed to upload $filename to S3"
                  fi
              fi
          done

          log "FTP to S3 sync completed"
          EOFSCRIPT

          # Replace variables in script
          sed -i "s/\${FTPUser}/${FTPUser}/g" /usr/local/bin/ftp-to-s3.sh
          sed -i "s/\${S3BucketName}/${S3BucketName}/g" /usr/local/bin/ftp-to-s3.sh

          chmod +x /usr/local/bin/ftp-to-s3.sh

          #add firewall exceptions for FTP ports
          ufw allow 21000-21100/tcp
          ufw allow 29720/tcp

          # Create log file
          touch /var/log/ftp-to-s3.log
          chmod 644 /var/log/ftp-to-s3.log

          # Verify vsftpd is running and listening on port 29720
          echo "Verifying vsftpd is listening on port 29720..."
          sleep 3

          MAX_RETRIES=10
          RETRY_COUNT=0
          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
              if ss -tuln | grep ":29720 " > /dev/null; then
                  echo "SUCCESS: vsftpd is listening on port 29720"
                  break
              fi
              echo "Port 29720 not listening yet, retrying ($((RETRY_COUNT+1))/$MAX_RETRIES)..."
              sleep 2
              RETRY_COUNT=$((RETRY_COUNT+1))
          done

          if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
              echo "WARNING: vsftpd may not be listening on port 29720 after $MAX_RETRIES attempts"
              echo "Checking vsftpd status..."
              systemctl status vsftpd || true
              echo "Checking vsftpd logs..."
              journalctl -u vsftpd -n 50 || true
              echo "Checking if port is in use..."
              ss -tuln | grep 29720 || echo "Port 29720 not in use"
              echo "Continuing with setup - port may become available later..."
          fi

          # Add cron job (runs every 2 minutes)
          echo "Setting up cron job for S3 sync..."
          echo "*/2 * * * * /usr/local/bin/ftp-to-s3.sh" | crontab -

          echo "Starting cron service..."
          systemctl start cron
          systemctl enable cron

          # Restart vsftpd to ensure it picks up all configuration changes
          echo "Restarting vsftpd service to apply final configuration..."
          sleep 60
          systemctl restart vsftpd
          sleep 2

          # Verify vsftpd is running after restart
          if systemctl is-active --quiet vsftpd; then
              echo "SUCCESS: vsftpd is running after restart"
              ss -tuln | grep 29720 || echo "WARNING: Port 29720 not yet visible (may take a moment)"
          else
              echo "ERROR: vsftpd failed to start after restart"
              systemctl status vsftpd || true
          fi

          # Create ready marker
          echo "FTP_SERVER_READY" > /tmp/ftp-ready
          echo "========================================="
          echo "UserData script completed successfully"
          echo "Timestamp: $(date)"
          echo "========================================="

      Tags:
        - Key: Name
          Value: FTP-Server

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref FTPServer
    Export:
      Name: !Sub '${AWS::StackName}-InstanceId'

  PublicIP:
    Description: Public IP address of FTP server
    Value: !GetAtt FTPServer.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}-PublicIP'

  FTPPort:
    Description: FTP port
    Value: 29720
    Export:
      Name: !Sub '${AWS::StackName}-FTPPort'

  LogGroupName:
    Description: CloudWatch Log Group name
    Value: !Ref FTPLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-LogGroup'
